name: flutter_holo_date_picker
description: A Flutter package of Datepicker that looks like Holo Theme in Android.
version: 1.0.6
homepage: https://github.com/kfiross/flutter_holo_date_picker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: